#!/usr/bin/env python

import argparse
import sys

def parse_args():
    parser = argparse.ArgumentParser()
    parser.add_argument("number", type=lambda x: int(x, 0),
                        help="What we want to see the bits of")
    return parser.parse_args()

def main():
    args = parse_args()

    print "|   28   24 |   20   16 |   12    8 |   4     0 |"
    sys.stdout.write("| ")
    for i in xrange(8):
        nibble = (args.number >> (28 - 4 * i)) & 0xF
        for j in xrange(4):
            bit = (nibble >> (3 - j)) & 0x1
            sys.stdout.write(str(bit))
        if i % 2 == 1:
            sys.stdout.write(" | ")
        else:
            sys.stdout.write(" ")
    print ""

    for i in xrange(4):
        nibble1 = args.number >> (24 - 8 * i + 4) & 0xF
        nibble2 = args.number >> (24 - 8 * i) & 0xF
        sys.stdout.write("| {:^4} {:^4} ".format("%01X" % nibble1, "%01X" % nibble2))
    print "|"

if __name__ == '__main__':
    main()
