#!/bin/sh

for k in $(git branch $@ | sed -r -e 's/^..//;s/ .*$//' | sort); do
    git --no-pager show --no-patch --pretty=format:"%Cgreen%<(15,trunc)%cr  %Cblue%h  %Creset%<(40,trunc)%s  $k%n" $k --
done
