#!/bin/sh

for k in `git branch $@ | sed -r -e 's/^..//;s/ .*$//'`
do
    line=`git show --pretty=format:"%Cgreen%cr\t%Cblue%t %Creset%<(40,trunc)%s" $k | head -n 1`
    echo "$line\t$k"
done | sort -r
