#!/bin/bash

# Make sure that arguments are expanded to string
ARGS="$@"
if [ -z "$ARGS" ]; then
    echo "Usage: git who [REV-RANGE] FILE..."
    exit 0
fi

git rev-parse $1 -- >/dev/null 2>&1
if [ $? -ne 0 ]; then
    REVISIONS="`git rev-list --max-parents=0 HEAD`.."
else
    REVISIONS=$1
    shift
fi

echo "Recent:"
git log --pretty="%cd|%ae" --date=short $REVISIONS -- $@ \
    | uniq \
    | head -n 10 \
    | column -ts '|' \
    | sed 's/^/  /'

echo -e "\nTop Committers:"
git log --pretty="%ae" $REVISIONS -- $@ \
    | sort \
    | uniq -c \
    | sort -nr \
    | head -n 10 \
    | column -t \
    | sed 's/^/  /'
