#!/bin/sh

list_mine() {
    ME=$(jira me)
    jira issue list --assignee $ME --plain --columns 'TYPE,KEY,SUMMARY,STATUS,PRIORITY' "$@"
}

list_all() {
    jira issue list --plain --columns 'TYPE,KEY,SUMMARY,STATUS,ASSIGNEE,PRIORITY' "$@"
}

filters() {
    FUNCTION="$1"
    FILTER="$2"
    shift 2
    case "$FILTER" in
        active)
            $FUNCTION --jql 'status in ("In Progress", "Ready for QA", "Reviewed")' -t'~Epic' --order-by 'status' --reverse "$@"
            ;;
        bugs)
            $FUNCTION --status '~Closed' --type 'Bug' "$@"
            ;;
        todo)
            $FUNCTION --status 'To Do' --type '~Epic' "$@"
            ;;
        *)
            $FUNCTION --status '~Closed' --type '~Epic' $FILTER "$@"
            ;;
    esac
}

WHO="$1"
shift 1
case "$WHO" in
    all)
        filters list_all "$@"
        ;;
    mine)
        list_mine --status '~Closed' "$@"
        ;;
    my)
        filters list_mine "$@"
        ;;
    *)
        jira "$@"
        ;;
esac
