#!/usr/bin/env python3
#
# Usage: saltlick-decrypt-logs <log.tgz.enc>
#
# This will attempt decrypt and output log.tgz in the
# same directory as the original.

import argparse
import os
import subprocess


def do_decrypt(args):
    dstname, _ext = os.path.splitext(args.encfile)
    home = os.getenv("HOME")
    cmd = f"{home}/.cargo/bin/saltlick decrypt -i '{args.encfile}' -o '{dstname}'"
    print(cmd)
    subprocess.check_call(cmd, shell=True)


def main():
    parser = argparse.ArgumentParser("saltlick-decrypt-logs")
    parser = argparse.ArgumentParser(description='')
    parser.add_argument("encfile")
    args = parser.parse_args()
    do_decrypt(args)


if __name__ == '__main__':
    main()
