#!/bin/sh

list_installed() {
    cargo install --list | tr -d ':' | sed '/^ /d' | sort
}

PACKAGES="
cargo-count
cargo-watch
racer
ripgrep
rustfmt
rusty-tags
"

BEFORE=$(list_installed)
for pkg in $PACKAGES; do
    cargo install --force $pkg
done
AFTER=$(list_installed)

echo "Before:"
echo "$BEFORE" | sed 's/^/    /'
echo
echo "After:"
echo "$AFTER" | sed 's/^/    /'
