scriptencoding utf-8

" {{{ Colorscheme settings
colorscheme darkblue
" }}}

" Remove unneeded menu bar and toolbar
set guioptions-=m
set guioptions-=T

" vim: set fenc=utf-8 tw=80 sw=2 sts=2 et foldmethod=marker :
