scriptencoding utf-8

" Override brain-dead Windows visual mode
behave xterm

" Set up vundle
set nocompatible
filetype off
set rtp+=~/.vim/vundle.vim/
set rtp+=~/vimfiles/vundle.vim/
call vundle#rc()

" Vundle bundles

" Sensible Defaults
Bundle 'tpope/vim-sensible'

" Motions/Text Objects
Bundle 'bkad/CamelCaseMotion'
Bundle 'Lokaltog/vim-easymotion'
Bundle 'wellle/targets.vim'
Bundle 'tpope/vim-surround'
Bundle 'vim-scripts/argtextobj.vim'
Bundle 'justinmk/vim-sneak'
Bundle 'terryma/vim-expand-region'
Bundle 'vim-scripts/matchit.zip'

" UI enhancements
Bundle 'corntrace/bufexplorer'
Bundle 'bling/vim-airline'
Bundle 'bling/vim-bufferline'
Bundle 'scrooloose/nerdtree'
Bundle 'majutsushi/tagbar'
Bundle 'vim-scripts/YankRing.vim'

" Syntax/Indenting
Bundle 'dagwieers/asciidoc-vim'
Bundle 'tfnico/vim-gradle'
Bundle 'tpope/vim-markdown'
Bundle 'vim-scripts/ebnf.vim'
Bundle 'wting/rust.vim'
Bundle 'vim-scripts/groovyindent'
Bundle 'vim-scripts/indentpython.vim'
Bundle 'othree/html5.vim'
Bundle 'godlygeek/tabular'
Bundle 'kergoth/vim-bitbake'

" Command execution
Bundle 'krisajenkins/vim-pipe'
Bundle 'tpope/vim-dispatch'

" Coding
Bundle 'dantler/vim-alternate'
Bundle 'tpope/vim-endwise'
Bundle 'tpope/vim-commentary'
Bundle 'AndrewRadev/splitjoin.vim'

" Other
Bundle 'vim-scripts/vimwiki'
Bundle 'vim-scripts/visSum.vim'
Bundle 'tpope/vim-fugitive'
Bundle 'vim-scripts/bufkill.vim'

filetype plugin indent on

" =====[General settings]=====
set nobackup                   " Don't leave cruft all over the place
set nowritebackup              " Don't leave cruft all over the place
set encoding=utf-8             " Use UTF-8 by default
set ff=unix                    " If not unix formatted, I want to know
set splitbelow                 " Open new splits at bottom
set splitright                 " Open new vsplits at the right
set modeline
set ignorecase                 " Ignore case in searches...
set smartcase                  " ...unless I specify a capital letter
set hlsearch
set showmatch

" =====[Autocommands]=====
if has("autocmd")
  " Put these in an autocmd group, so that we can delete them easily.
  augroup vimrcEx
  au!

  " For all text files set 'textwidth' to 78 characters.
  autocmd FileType text setlocal textwidth=78

  " When editing a file, always jump to the last known cursor position.
  " Don't do it when the position is invalid or when inside an event handler
  " (happens when dropping a file on gvim).
  " Also don't do it when the mark is in the first line, that is the default
  " position when opening a file.
  autocmd BufReadPost *
    \ if line("'\"") > 1 && line("'\"") <= line("$") |
    \   exe "normal! g`\"" |
    \ endif

  autocmd FileType python let b:vimpipe_command="python -"

  augroup END

endif " has("autocmd")

" =====[Suffix settings]=====
" When doing tab completion, give the following files lower priority.
set suffixes+=.info,.aux,.log,.dvi,.bbl,.out,.o,.lo

" =====[Line number settings]=====
if v:version >= 700
  set numberwidth=3
endif
if v:version >= 703
  set relativenumber
endif

" =====[Command mappings]=====
inoremap kj <Esc>
inoremap <Esc> <nop>
nnoremap <silent><C-j> :set paste<CR>m`o<Esc>``:set nopaste<CR>
nnoremap <silent><C-k> :set paste<CR>m`O<Esc>``:set nopaste<CR>
nnoremap <silent><C-h> :tabprev<CR>
nnoremap <silent><C-l> :tabnext<CR>
nnoremap <Space> i_<Esc>r
nnoremap <leader>q :nohlsearch<CR>
nnoremap <leader>ev :split $MYVIMRC<CR>
nnoremap <leader>sv :source $MYVIMRC<CR>

nnoremap <leader>wo :VimwikiIndex<CR> :VimwikiGoto work/index<CR>
nnoremap <leader>d :VimwikiIndex<CR> :VimwikiGoto Brain Dump<CR>

" Replace normal buffer unload/delete/wipe mappings with bufkill.vim
cabbrev bun BUN
cabbrev bd BD
cabbrev bw BW

" CTRL-U in insert mode deletes a lot.  Use CTRL-G u to first break undo,
" so that you can undo CTRL-U after inserting a line break.
inoremap <C-U> <C-G>u<C-U>

" Add a 'yank entire buffer to system clipboard' command
nnoremap <leader>a :1,$y+<CR>

" Wipe the current buffer
nnoremap <leader>x :BW<CR>

" =====[Vimwiki options]=====
let g:personal_dropbox_loc = $DROPBOX
let wiki_1 = {}
let wiki_1.path = g:personal_dropbox_loc . '/vimwiki/'
let wiki_1.path_html = g:personal_dropbox_loc . '/vimwiki_html/'
let wiki_1.template_path = g:personal_dropbox_loc . '/etc/vimwiki_templates/'
let wiki_1.template_default = 'default'
let wiki_1.template_ext = '.html'
let wiki_1.nested_syntaxes = {
      \ 'c++': 'cpp',
      \ 'ebnf': 'ebnf',
      \ 'groovy': 'groovy',
      \ 'java': 'java',
      \ 'markdown': 'markdown',
      \ 'python': 'python',
      \ 'rust': 'rust',
      \ 'sh': 'sh',
      \ 'verilog': 'verilog',
      \ }

let g:vimwiki_list = [wiki_1]

" =====[Airline options]=====
let g:airline_theme='powerlineish'
let g:airline_left_sep=''
let g:airline_right_sep=''
let g:airline_section_z=''
let g:airline#extensions#bufferline#enabled = 1
let g:airline#extensions#hunks#enabled = 1
let g:airline#extensions#tagbar#enabled = 1

" =====[Custom scratch buffers]=====
" http://dhruvasagar.com/2014/03/11/creating-custom-scratch-buffers-in-vim
function! ScratchEdit(cmd, options)
    exe a:cmd tempname()
    setl buftype=nofile bufhidden=wipe nobuflisted
    if !empty(a:options) | exe 'setl' a:options | endif
endfunction

command! -bar -nargs=* Sedit call ScratchEdit('edit', <q-args>)
command! -bar -nargs=* Ssplit call ScratchEdit('split', <q-args>)
command! -bar -nargs=* Svsplit call ScratchEdit('vsplit', <q-args>)
command! -bar -nargs=* Stabedit call ScratchEdit('tabe', <q-args>)

" =====[Expand region mappings]=====
vmap v <Plug>(expand_region_expand)
vmap <C-v> <Plug>(expand_region_shrink)

" =====[Use persistent undo ]=====
if has('persistent_undo')
  set undodir=$HOME/.vim_undo
  set undolevels=5000
  set undofile
endif

" =====[Highlight offensive characters]=====
" (uBB is right double angle, uB7 is middle dot)
exec "set lcs=tab:\uBB\uBB,trail:\uB7,nbsp:~"

augroup HighlightOffensive
    autocmd!
    autocmd BufEnter  *       set list
    autocmd BufEnter  *.txt   set nolist
    autocmd BufEnter  *       if !&modifiable
    autocmd BufEnter  *           set nolist
    autocmd BufEnter  *       endif
augroup END

" =====[Correct common mistyped words]=====
iab  retrun  return
iab   pritn  print
iab     teh  the

" =====[Highlight spelling on request]=====
set spelllang=en_us
nnoremap <leader>sp :setlocal invspell<CR>

" =====[NERDTree Options]=====
let NERDTreeChristmasTree=1
let NERDTreeCascadeOpenSingleChildDir=1
let NERDTreeAutoDeleteBuffer=1
nnoremap <leader>n :NERDTree<CR>

" =====[TagBar Options]=====
nnoremap <leader>t :TagbarToggle<CR>

" vim: set fenc=utf-8 tw=80 sw=2 sts=2 et foldmethod=marker :
