alias bc="bc -l"
alias c="clear"
alias df="df -h"
alias ga="garden"
alias grep="grep --colour=auto"
alias lq="ls -A"
alias rmf="rm -rf"
alias rustfmt-nightly="rustup run nightly rustfmt --config-path ~/.nightly-rustfmt.toml --emit files --edition 2018"
alias st="smartthings"
alias su="su -"
alias tmux="tmux -2"
alias vimupdate="nvim +PackerSync"
alias x="tar axf"

command -v gping >/dev/null 2>&1 && alias ping="gping"
command -v nvim >/dev/null 2>&1 && alias vim="nvim"
command -v xdg-open >/dev/null 2>&1 && alias open="xdg-open"
